version: '3.8'

services:
  db:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "6543:5432"
  pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4:5.5
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: secret
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8080:80"
   volumes:
     - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: